[versions]
poi = "5.3.0"
poi-ooxml = "5.3.0"
commonsLang = "3.12.0"

junit = "5.10.0"
assertJ = "3.24.2"

[libraries]
poi = { module = "org.apache.poi:poi", version.ref = "poi" }
poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poi-ooxml" }
commonsLang = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang" }

junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
assertJ = { module = "org.assertj:assertj-core", version.ref = "assertJ" }

[plugins]
